services:
  - type: web
    name: cool-route-api
    env: python
    plan: free
    buildCommand: python -m pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /healthcheck
